# Additional configuration and default values at https://github.com/gakonst/foundry/tree/master/config


# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
# solc_version = '0.8.0'
[profile.default]
remappings = [
  "ds/=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/contracts/",
]


[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
